version: "3.8"
services:
  shadowsocks:
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    volumes:
      - ./shadowsocks.json:/etc/shadowsocks-rust/config.json
    ports:
      - "127.0.0.1:8388:8388"
  kcptun:
    image: ghcr.io/avalonwot/kcptun-docker:master
    volumes:
      - ./kcptun.json:/etc/kcptun/config.json
    network_mode: "host"
    entrypoint: ["server", "-c", "/etc/kcptun/config.json"]

